# autonomous_hunter.py
import asyncio
import time
import os
import json
import re
import httpx
from pathlib import Path
from dotenv import load_dotenv

# --- PACKAGE-AWARE UTILITY IMPORTS ---
from utils.hunter_utils import (
    is_canonical_address, fetch_source_code, triage_contract_ast, triage_contract,
    get_contract_creator, resolve_ens_name, search_github_for_address, send_discord_alert,
    check_economic_viability
)
from utils.anvil_verifier import run_dynamic_verification

# --- 0. PATH RESOLUTION (OS-AGNOSTIC ROOT CONTEXT) ---
BASE_DIR = Path(__file__).parent.resolve()  # SCRIPT_DIR is already the project root folder

# Load secret keys to access ALCHEMY_RPC_URL and API targets
load_dotenv(dotenv_path=BASE_DIR / ".env")

LOCAL_API_URL = "http://127.0.0.1:8000/scan"

QUEUE_FILE = BASE_DIR / "target_queue.txt"
WAITING_ROOM_FILE = BASE_DIR / "waiting_room.json"
REPORTS_DIR = BASE_DIR / "reports"
LOGS_DIR = BASE_DIR / "logs"

os.makedirs(REPORTS_DIR, exist_ok=True)
os.makedirs(LOGS_DIR, exist_ok=True)

# ==========================================
# 📥 QUEUE HELPERS
# ==========================================
def load_waiting_room():
    if os.path.exists(WAITING_ROOM_FILE):
        try:
            with open(WAITING_ROOM_FILE, 'r') as f: return json.load(f)
        except json.JSONDecodeError: return {}
    return {}

def save_waiting_room(data):
    with open(WAITING_ROOM_FILE, 'w') as f: json.dump(data, f, indent=4)

def get_target_from_queue():
    if not os.path.exists(QUEUE_FILE) or os.path.getsize(QUEUE_FILE) == 0: return None
    try:
        with open(QUEUE_FILE, 'r') as f: lines = f.readlines()
        if not lines: return None
        
        target = None
        remaining_lines = []
        for line in lines:
            if not target and line.strip().startswith('0x'): target = line.strip()
            else: remaining_lines.append(line)
                
        if target:
            with open(QUEUE_FILE, 'w') as f: f.writelines(remaining_lines)
        return target
    except Exception:
        return None

# ==========================================
# 🔬 STATE-CONSISTENCY & STORAGE-FLOW FILTER
# ==========================================
def verify_state_consistency(source_code, report_text):
    """
    Validates engine-flagged access control and modifier omissions against internal storage slots.
    Bypasses false positives generated by Diamond/AppStorage library internal constraints.
    """
    storage_pointers = ["_getStorage()", "DiamondStorage", "AppStorage", "ds.manager", "position.slot"]
    has_internal_storage_routing = any(p in source_code for p in storage_pointers)
    
    is_modifier_alert = any(term in report_text.lower() for term in [
        "unprotected external function", "missing access control", 
        "missing modifier", "lack of authority modifiers"
    ])
    
    if is_modifier_alert and has_internal_storage_routing:
        internal_auth_checks = [r"msg\.sender\s*==\s*", r"require\s*\(.*manager", r"AuthLibrary\.", r"assert\s*\(.*owner"]
        for pattern in internal_auth_checks:
            if re.search(pattern, source_code):
                print("🛡️ [STATE-CONSISTENCY] Intercepted proxy storage library internal authorization check.")
                return False  
                
    return True  

# ==========================================
# 🧠 CORE SCANNING LOGIC (ASYNC ARCHITECTURE)
# ==========================================
async def scan_address(client: httpx.AsyncClient, address: str, force: bool = False) -> str:
    print(f"\n⚡ Ingesting target: {address}")
    
    # --- EDGE INTERCEPT 1: Canonical Token Whitelist Matrix ---
    if is_canonical_address(address):
        print(f"🛡️ [WHITELIST-INTERCEPT] Skipping {address} - Verified immutable asset pool ledger.")
        return "DONE"

    # --- NEW ASYNC OSINT DIRECTIVE: AUTOMATED ECONOMIC TRIAGE ---
    # Instantly discards zero-value configurations before hitting inference models
    if not force and not await check_economic_viability(address, min_eth=0.01):
        return "DONE"

    # --- INGESTION PHASE: Fetch Source Code Payload ---
    # (Kept synchronous as it relies on connection-pooled third-party retrieval)
    source_code = fetch_source_code(address)
    if not source_code:
        print(f"❌ [FETCH-ERROR] Could not isolate source layout payload for {address}. Dropping target.")
        return "DONE" 

    # --- EDGE INTERCEPT 2: AST Gatekeeper Regex Triage Check ---
    if not triage_contract_ast(source_code, force_bypass=force):
        print(f"🗑️ [AST-FILTER-DROP] Dropping {address} - Invariant code clone detected (No loops/callbacks).")
        return "DONE"

    # --- HISTORICAL INVARIANT SCRIPT TRIAGE MATCHING ---
    if not triage_contract(source_code) and not force:
        print(f"⏭️ Skipped {address} - Baseline structural code invariants missing.")
        return "DONE"

    # --- OSINT BOUNCER CHECK WINDOWS ---
    print(f"🕵️ Running OSINT checks before Engine analysis...")
    creator_wallet, tx_hash = get_contract_creator(address)
    
    if str(creator_wallet).lower() in ["none", "unknown", "", "null"]:
        print(f"   [BLOCKED] 🗑️ Dropping {address} (Factory Deployed / Infrastructure).")
        return "DONE"
        
    ens_name = resolve_ens_name(creator_wallet) if creator_wallet else "Unknown"
    github_repo = search_github_for_address(address)
    
    if ("Anonymous Wallet" in ens_name or "Unknown" in ens_name) and ("No public repo found" in github_repo or "Failed" in github_repo):
        print(f"   [BLOCKED] 🗑️ Dropping {address} (No Identity + No Repo = No Bounty).")
        with open(LOGS_DIR / "dropped_scams.txt", "a") as f:
            f.write(f"{time.strftime('%Y-%m-%d %H:%M:%S')} - {address} (Low Signal)\n")
        return "DONE" 

    # --- INFERENCE ENGINE ROUTING LAYER (NON-BLOCKING) ---
    print(f"🎯 [HIGH-SIGNAL] Approved! Passing {address} to 0xNeural V2 Agentic Core...")
    try:
        # Asynchronously transmit contract payload to back-end worker node
        response = await client.post(LOCAL_API_URL, json={"source_code": source_code}, timeout=120.0)
        
        if response.status_code == 200:
            res_json = response.json()
            
            # Catch deterministic structured back-end drop instructions
            if res_json.get("status") == "dropped":
                print(f"   [TRASHED] 📉 Multi-Agent Filter: {res_json.get('reason')}")
                return "DONE"
                
            report = res_json.get('report', '')
            
            if not verify_state_consistency(source_code, report):
                print(f"   [TRASHED] 📉 Invariant Filter Override: Access check resides in library storage frame.")
                with open(LOGS_DIR / "filtered_false_positives.txt", "a") as f:
                    f.write(f"{time.strftime('%Y-%m-%d %H:%M:%S')} - {address} (Internal Proxy Library Access Protection Enforced)\n")
                return "DONE"

            # --- NEW ANVIL SANDBOX PROPERTY-BASED FUZZ FILTER ---
            rpc_url = os.getenv("ALCHEMY_RPC_URL")
            if not rpc_url:
                print("   ⚠️ [WARNING] ALCHEMY_RPC_URL missing from .env. Skipping Anvil Sandbox verification.")
                is_verified = True 
            else:
                print("   🧪 Routing to Anvil Sandbox for automated property fuzzing validation...")
                is_verified = await run_dynamic_verification(report, rpc_url)

            if is_verified:
                print(f"🎯 ZERO-DAY CONFIRMED BY PROPERTY FUZZER! Compiling localized advisory report...")
                filename = REPORTS_DIR / f"VULN_{address}.md"
                osint_data = (
                    f"\n\n## 🕵️ Automated OSINT Dossier\n"
                    f"- **Deployer Wallet:** `{creator_wallet}`\n"
                    f"- **Deployer ENS:** `{ens_name}`\n"
                    f"- **Creation Tx:** `{tx_hash}`\n"
                    f"- **Likely GitHub Repo:** {github_repo}\n"
                )
                
                with open(filename, 'w', encoding='utf-8') as f:
                    f.write(f"# Audit Report: {address}\n**Scan Date:** {time.strftime('%Y-%m-%d %H:%M:%S')}\n**High Value Logic:** True\n\n")
                    clean_report = report.replace("High Value Logic: True\n", "").strip()
                    f.write(clean_report)
                    f.write(osint_data)
                    
                send_discord_alert(address, clean_report, osint_data)
                return "DONE"
            else:
                print("   🗑️ FALSE POSITIVE FILTERED. Sandbox fuzzer failed to break contract properties. Dropping.")
                with open(LOGS_DIR / "filtered_false_positives.txt", "a") as f:
                    f.write(f"{time.strftime('%Y-%m-%d %H:%M:%S')} - {address} (Failed Property Fuzz execution)\n")
                return "DONE"
            
        elif response.status_code == 500:
            print(f"   ⚠️ [API ERROR] Server returned internal fault code 500. Verification limit threshold reached.")
            return "RATE_LIMIT"
        else:
            print(f"❌ Engine error code returned: {response.status_code}")
            return "DONE"
            
    except httpx.ConnectError:
        print("❌ System Error: Cannot resolve backend connection. Verify that app.py uvicorn server is active.")
        return "DONE"

# ==========================================
# 📥 QUEUE MANAGEMENT (CONCURRENT ARCHITECTURE)
# ==========================================
async def run_queue_mode():
    print(f"🦇 Asynchronous Queue Engine Active. Watching '{QUEUE_FILE}'...")
    if not os.path.exists(QUEUE_FILE): open(QUEUE_FILE, 'w').close()

    MAX_RETRIES = 12 
    last_retry_time = 0
    RETRY_INTERVAL = 300 

    # Open persistent asynchronous HTTP connection client session pool
    async with httpx.AsyncClient() as client:
        while True:
            try:
                pending_retries = load_waiting_room()
                target = get_target_from_queue()
                
                if target:
                    if target not in pending_retries:
                        status = await scan_address(client, target)
                        
                        if status == "RATE_LIMIT":
                            print(f"   [WAITING] ⏳ Moving {target} to Waiting Room until API quota resets.")
                            pending_retries[target] = 0
                            save_waiting_room(pending_retries)
                    
                    await asyncio.sleep(1.0)
                else:
                    await asyncio.sleep(10.0)

                current_time = time.time()
                if pending_retries and (current_time - last_retry_time > RETRY_INTERVAL):
                    print(f"\n🔄 Checking {len(pending_retries)} rate-limited targets inside the Waiting Room...")
                    
                    for addr in list(pending_retries.keys()):
                        status = await scan_address(client, addr)
                        
                        if status == "RATE_LIMIT":
                            print(f"   [WAITING] ⏳ API quota limit still active. Retry index: {pending_retries[addr] + 1}/{MAX_RETRIES}")
                            pending_retries[addr] += 1
                            
                            if pending_retries[addr] >= MAX_RETRIES:
                                print(f"   [TIMEOUT] 🗑️ Purging {addr} from state tracker - Exceeded retry limit boundaries.")
                                del pending_retries[addr]
                        else:
                            del pending_retries[addr]
                            
                        await asyncio.sleep(1.0) 
                        
                    save_waiting_room(pending_retries)
                    last_retry_time = time.time()

            except KeyboardInterrupt:
                print("\n👋 Halting Hunter execution loop.")
                break
            except Exception as e:
                print(f"❌ Ingestion loop fault: {e}")
                await asyncio.sleep(10.0)

async def main():
    import argparse
    parser = argparse.ArgumentParser(description="0xNeural V2 Autonomous Hunter")
    parser.add_argument("target", nargs="?", help="Contract address, file path, or 'queue'")
    parser.add_argument("--force", action="store_true", help="Skip triage and scan regardless of logic complexity")
    args = parser.parse_args()

    if not args.target or args.target == "queue":
        await run_queue_mode()
    elif os.path.isfile(args.target):
        with open(args.target, 'r') as f:
            addresses = [line.strip() for line in f if line.strip().startswith('0x')]
        async with httpx.AsyncClient() as client:
            for addr in addresses:
                await scan_address(client, addr, force=args.force)
                await asyncio.sleep(1.0)
    else:
        async with httpx.AsyncClient() as client:
            await scan_address(client, args.target, force=args.force)

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\n👋 Process aborted cleanly.")