# generate_proof.py
import os

REPORTS_DIR = "proof_of_concept_reports"
os.makedirs(REPORTS_DIR, exist_ok=True)

# We use helper constants to create code block tags dynamically 
# This prevents the markdown renderer from breaking your code view container
B = "```"
S = "solidity"
V = "vyper"

# Standard report constructor mapping clean text arrays safely
report_blueprints = {
    "UNHANDLED_RETURN_STATE.md": [
        "# Vulnerability Report: Incomplete Integration Tracking via Unhandled Interface Payload",
        "",
        "**Vulnerability Category:** Unhandled Return Value / Atomic Inconsistency",
        "**Severity:** Medium-High",
        "**Impact:** Denial of Service (DoS) / Permanent Lifecycle Lock-up during unallocation steps.",
        "",
        "---",
        "",
        "## 1. Technical Analysis",
        "The target integration contract functions as an orchestration layer interacting with external components via an abstract liquidity bridge workflow. During finalization inside `completeUnallocate`, the contract triggers an external call to recover underlying backing assets:",
        "",
        f"{B}{S}",
        "// Vulnerable Implementation",
        "IAlephVaultRedeem(_alephVault).syncRedeem(_p); ",
        "",
        "// Assumptions made on stale calculations",
        "_amount = _userPendingAmount;",
        f"{B}",
        "",
        "The external contract interface explicitly defines a return payload (`uint256 _assets`) indicating the exact number of tokens transferred to the calling contract frame during execution. However, this return value is completely unhandled. The contract assumes a static 1:1 delivery matching the original, stale estimation (`_userPendingAmount`) computed during the initial step.",
        "",
        "If the underlying vault suffers from pool slippage, fee-on-transfer deductions, rebalancing parameters, or strategic asset losses, the actual transferred balance will drop below the hardcoded calculation. The contract then attempts to pass the full estimated calculation to a downstream `StrategyManager` layer, forcing a transaction rollback due to insufficient real balances (`ERC20InsufficientBalance`).",
        "",
        "---",
        "",
        "## 2. Theoretical Exploit Scenario",
        "1. A user initiates an unallocation sequence based on a calculated estimation.",
        "2. The external vault experiences an operational variance or strategy loss, returning fewer assets than estimated during settlement execution.",
        "3. The contract ignores the real returned token payload, keeping its ledger records anchored to the stale estimate.",
        "4. The execution block attempts to forward the estimated amount to an external strategy manager. The frame runs out of real backing assets, triggering an immediate low-level ERC20 transfer failure and locking the user out of all subsequent redemption pathways because the transaction checks are executed within an atomic block frame.",
        "",
        "---",
        "",
        "## 3. Remediation",
        "Capture the real return payload dynamically and update state records to reflect verified balances instead of cached estimates:",
        "",
        f"{B}{S}",
        "// Capture the actual amount of underlying assets returned and transferred by the vault",
        "uint256 _actualAmountReceived = IAlephVaultRedeem(_alephVault).syncRedeem(_p);",
        "if (_actualAmountReceived == 0) revert NoTokensReceived();",
        "",
        "// Enforce logic parameters to match verified balances instead of cached estimates",
        "_amount = _actualAmountReceived;",
        "",
        "// Update storage only after successful and full redemption",
        "$.pendingUnallocate[msg.sender][_alephVault] = 0;",
        "$.totalPendingUnallocate[_alephVault] -= _userPendingAmount;",
        f"{B}"
    ],

    "MISSING_ACCESS_CONTROL_BRIDGE.md": [
        "# Vulnerability Report: Missing Access Control on Cross-Chain Messaging Endpoint",
        "",
        "**Vulnerability Category:** Missing Access Control",
        "**Severity:** High",
        "**Impact:** Economic Drain / Arbitrary Cross-Chain Execution Payload Injection",
        "",
        "---",
        "",
        "## 1. Technical Analysis",
        "The cross-chain messaging adapter implementation exposes an external execution endpoint named `forwardMessage` designed to pass arbitrary message payloads across network bounds using a low-level cross-chain infrastructure provider interface (e.g., LayerZero Endpoint). The contract handles native transaction gas pricing inside the frame using its own stored balance pools:",
        "",
        f"{B}{S}",
        "function forwardMessage(",
        "    uint16 nativeChainId,",
        "    address receiver,",
        "    bytes calldata message,",
        "    bytes calldata adapterParams",
        ") external payable returns (address, uint64) {",
        "    // Computes native fees based on parameters",
        "    (uint256 nativeFee, ) = LZ_ENDPOINT.estimateFees(nativeChainId, receiver, message, false, adapterParams);",
        "    require(nativeFee <= address(this).balance, \"Errors: NOT_ENOUGH_VALUE_TO_PAY_BRIDGE_FEES\");",
        "",
        "    // Dispatches message using contract funds",
        "    LZ_ENDPOINT.send{value: nativeFee}(nativeChainId, abi.encodePacked(receiver, address(this)), message, payable(address(this)), address(0), adapterParams);",
        "}",
        f"{B}",
        "",
        "The core execution endpoint completely lacks access control modifiers (such as `onlyOwner`, `onlyRole`, or an authorized controller check). While the architecture intends for this endpoint to be used exclusively by an upstream administrative manager component, the absence of an explicit authorization filter leaves it exposed to arbitrary open public invocation.",
        "",
        "---",
        "",
        "## 2. Theoretical Exploit Scenario",
        "1. An unprivileged actor constructs a transaction targeting the unshielded `forwardMessage` method.",
        "2. The attacker inputs arbitrary execution call structures alongside a target destination chain signature.",
        "3. The adapter accepts the incoming call block, draws native assets from its internal ledger pools to clear cross-chain transport fees, and dispatches the attacker's payload. This enables zero-cost network resource consumption and protocol balance draining.",
        "",
        "---",
        "",
        "## 3. Remediation",
        "Implement strict access control constraints to limit execution exclusively to the authorized controller component:",
        "",
        f"{B}{S}",
        "address public immutable CROSS_CHAIN_CONTROLLER;",
        "",
        "modifier onlyController() {",
        "    require(msg.sender == CROSS_CHAIN_CONTROLLER, \"Adapter: Unauthorized caller\");",
        "    _;",
        "}",
        "",
        "function forwardMessage(",
        "    uint16 nativeChainId,",
        "    address receiver,",
        "    bytes calldata message,",
        "    bytes calldata adapterParams",
        ") external payable onlyController returns (address, uint64) {",
        "    // Safe execution block logic",
        "}",
        f"{B}"
    ],

    "PROXY_FUNCTION_SHADOWING.md": [
        "# Vulnerability Report: Architectural Divergence through Proxy Function Shadowing",
        "",
        "**Vulnerability Category:** Access Control Bypass / Logic Shadowing",
        "**Severity:** Medium",
        "**Impact:** Proxy Takeover / Implementation Upgrade Hijacking",
        "",
        "---",
        "",
        "## 1. Technical Analysis",
        "The upgradeable proxy architecture implements a custom routing filter modifier designed to parse administrative interactions using the following non-standard pattern:",
        "",
        f"{B}{S}",
        "modifier proxyCallIfNotAdmin() {",
        "    if (msg.sender == _getAdmin() || msg.sender == address(0)) {",
        "        _;",
        "    } else {",
        "        _doProxyCall(); // Forces delegatecall to implementation",
        "    }",
        "}",
        f"{B}",
        "",
        "If an administrative method selector defined within the proxy (e.g., `upgradeTo`, `changeAdmin`) is targeted by a non-admin caller, the custom layout forwards the raw transaction via `delegatecall` directly to the underlying business logic implementation layer. This creates a functional selector clashing liability if the underlying implementation contains public methods with identical signatures that lack internal authorization checks.",
        "",
        "---",
        "",
        "## 2. Theoretical Exploit Scenario",
        "1. An unprivileged actor identifies that the `Proxy` contract uses a `proxyCallIfNotAdmin` modifier.",
        "2. The attacker inspects the implementation contract's bytecode and discovers an unprotected public function sharing an identical selector with one of the proxy's administrative functions (e.g., `upgradeTo(address)`).",
        "3. The attacker calls `upgradeTo` on the proxy. Since the sender is not the admin, execution jumps to the implementation via `delegatecall`, executing the logic in the context of the proxy's storage and overwriting the internal implementation pointer.",
        "",
        "---",
        "",
        "## 3. Remediation",
        "Enforce a strict binary separation standard where administrative proxy methods revert instantly if called by non-authorized entities, aligning with the standard transparent proxy pattern:",
        "",
        f"{B}{S}",
        "modifier onlyAdmin() {",
        "    require(msg.sender == _getAdmin(), \"Proxy: Caller is not admin\");",
        "    _;",
        "}",
        "",
        "function upgradeTo(address _implementation) public virtual onlyAdmin {",
        "    _setImplementation(_implementation);",
        "}",
        "",
        "function changeAdmin(address _admin) public virtual onlyAdmin {",
        "    _changeAdmin(_admin);",
        "}",
        f"{B}"
    ],

    "REENTRANCY_CALLBACK_BYPASS.md": [
        "# Vulnerability Report: Missing Reentrancy Guard on Flash Loan Callback Endpoint",
        "",
        "**Vulnerability Category:** Reentrancy / Check-Effects-Interactions Violation",
        "**Severity:** High",
        "**Impact:** Fund Exhaustion via Recursive Borrow Loops",
        "",
        "---",
        "",
        "## 1. Technical Analysis",
        "The transaction bundler asset manager utilizes external flash loan infrastructure providers to optimize multi-asset execution pathways. The contract implements an external receiver callback hook (`executeOperation`) to process assets returned by the liquidity pool during execution frames.",
        "",
        "While the contract's internal helper functions are wrapped with a localized `nonReentrant` modifier, the primary entrypoint invoked by the external flash loan pool lacks a protection guard:",
        "",
        f"{B}{S}",
        "// Vulnerable Entry Point Missing Guard",
        "function executeOperation(",
        "    address[] calldata assets,",
        "    uint256[] calldata amounts,",
        "    uint256[] calldata premiums,",
        "    address initiator,",
        "    bytes calldata params",
        ") external override(IAveFlashLoanReceiver) returns (bool) {",
        "    // Arbitrary external calls (WETH withdrawals, Uniswap Swaps) happen here",
        "    _weth.withdraw(amounts[0]);",
        "    address(_uniswapRouter).call{value: ethValue}(swapData);",
        "    ",
        "    // Internal function calls are protected, but parent is open",
        "    this.executeSell(params);",
        "}",
        f"{B}",
        "",
        "Because `executeOperation` itself is not guarded, an external component triggered during the swap sequence can execute a control-flow hijack, re-entering the parent framework before the active execution frame finalizes.",
        "",
        "---",
        "",
        "## 2. Theoretical Exploit Scenario",
        "1. An attacker coordinates an asset deployment that triggers an automated flash loan routing path.",
        "2. The landing platform executes an external transfer statement to an untrusted token/router address.",
        "3. The malicious receiver intercepts execution and calls back into `executeOperation`. Because the parent entrypoint lacks a reentrancy lock, the second call block triggers recursive resource generation actions within the same transaction frame, allowing the attacker to bypass state finalization checks.",
        "",
        "---",
        "",
        "## 3. Remediation",
        "Apply standard reentrancy locks directly to the callback interface signature block:",
        "",
        f"{B}{S}",
        "function executeOperation(",
        "    address[] calldata assets,",
        "    uint256[] calldata amounts,",
        "    uint256[] calldata premiums,",
        "    address initiator,",
        "    bytes calldata params",
        ") external override(IAaveFlashLoanReceiver) nonReentrant returns (bool) {",
        "    // Safe execution block logic",
        "}",
        f"{B}"
    ],

    "HARDCODED_GAS_FRAGILITY.md": [
        "# Vulnerability Report: Hardcoded Transmission Overhead Parameter Fragility",
        "",
        "**Vulnerability Category:** Hardcoded Invariant / Denial of Service (DoS) Risk",
        "**Severity:** Low / Informational",
        "**Impact:** Cross-Chain Messaging Stalls / Transaction Rollbacks",
        "",
        "---",
        "",
        "## 1. Technical Analysis",
        "The cross-chain messaging adapter interface relies on a constant, hardcoded execution value parameter designed to account for target gas delivery adjustments during cross-chain transaction transport tracking:",
        "",
        f"{B}{S}",
        "uint256 public constant RECEIVE_COST = 70_000;",
        f"{B}",
        "",
        "This constant value is added directly to user-supplied calculation inputs during price quotes and transaction shipping operations:",
        "- `relayer.quoteEVMDeliveryPrice(destinationId, 0, gasLimit + RECEIVE_COST)`",
        "- `relayer.sendPayloadToEvm{value: msg.value}(..., gasLimit + RECEIVE_COST, ...)`",
        "",
        "The core logical constraint is that EVM opcode gas costs are not static; network upgrades (e.g., hard forks repricing computational overhead like `SLOAD` or memory expansion costs) regularly alter execution economics. Hardcoding calculation constants inside an immutable architecture introduces long-term system fragility.",
        "",
        "---",
        "",
        "## 2. Theoretical Exploit Scenario",
        "1. A network upgrade alters the base gas costs of standard opcodes used within the receiving adapter logic on a target destination chain.",
        "2. The actual gas required to process the message preamble surpasses the hardcoded 70,000 gas limit barrier.",
        "3. All incoming cross-chain message deliveries drop cold on the destination chain due to immediate Out-of-Gas errors, causing a functional denial of service across the bridge architecture.",
        "",
        "---",
        "",
        "## 3. Remediation",
        "Transition the static constant parameter into an administrative storage slot variable protected by authorized setters:",
        "",
        f"{B}{S}",
        "uint256 public receiveCost = 70_000;",
        "",
        "function setReceiveCost(uint256 _newCost) external onlyAuth {",
        "    receiveCost = _newCost;",
        "}",
        f"{B}"
    ],

    "TRANSITIVE_PRIVILEGE_ESCALATION.md": [
        "# Vulnerability Report: Transitive Privilege Escalation via Over-Privileged Component Roles",
        "",
        "**Vulnerability Category:** Access Control / Structural Role Misconfiguration",
        "**Severity:** High",
        "**Impact:** Vault Takeover / Parameter Manipulation",
        "",
        "---",
        "",
        "## 1. Technical Analysis",
        "An asynchronous asset vault deployment factory contract instantiates individual user-facing investment vaults. As part of this deployment sequence, it grants an external helper component, the `AsyncRequestManager`, administrative rights (`ward` status) on the newly spawned vault:",
        "",
        f"{B}{S}",
        "AsyncVault vault = new AsyncVault{salt: salt}(poolId, scId, asset, token, root, asyncRequestManager);",
        "vault.rely(address(asyncRequestManager));",
        f"{B}",
        "",
        "The underlying vault contract utilizes a general authentication tracking design where *any* registered ward has full access to configuration methods (`file`). Because the helper component is granted wide administrative status instead of scoped parameters, it inherits total access to sensitive initialization properties—including the ability to re-route core system pointers:",
        "",
        f"{B}{S}",
        "function file(bytes32 what, address data) external virtual auth {",
        "    if (what == \"manager\") {",
        "        baseManager = IBaseRequestManager(data);",
        "    } else if (what == \"asyncRedeemManager\") {",
        "        asyncRedeemManager = IAsyncRedeemManager(data);",
        "    }",
        "}",
        f"{B}",
        "",
        "---",
        "",
        "## 2. Theoretical Exploit Scenario",
        "1. An operational vulnerability or arbitrary execution bug is discovered inside the external manager contract layer.",
        "2. An attacker utilizes the manager's execution frame to call back into the vault: `vault.file(\"manager\", maliciousAddress)`.",
        "3. Because the vault recognizes the manager's address as an authorized ward, the transaction clears access control, allowing the attacker to replace system structures and hijack deposit/redeem logic parameters.",
        "",
        "---",
        "",
        "## 3. Remediation",
        "Enforce precise separation parameters by restricting contract layout updates exclusively to the master governance component:",
        "",
        f"{B}{S}",
        "function file(bytes32 what, address data) external virtual {",
        "    require(msg.sender == address(root), \"Vault: Only root governance can reconfigure\");",
        "    if (what == \"manager\") {",
        "        baseManager = IBaseRequestManager(data);",
        "    } else if (what == \"asyncRedeemManager\") {",
        "        asyncRedeemManager = IAsyncRedeemManager(data);",
        "    } else {",
        "        revert FileUnrecognizedParam();",
        "    }",
        "}",
        f"{B}"
    ],

    "CROSS_CONTRACT_INITIALIZATION_BLOCK.md": [
        "# Vulnerability Report: Strict Initialization Dependency Order Intercept",
        "",
        "**Vulnerability Category:** Operational Risk / Initialization Deadlock",
        "**Severity:** Informational / Low",
        "**Impact:** Denial of Service (DoS) on Initialization Workflows",
        "",
        "---",
        "",
        "## 1. Technical Analysis",
        "The deposit orchestration management contract relies on an external factory deployment component to create dynamic escrow vaults during user interaction loops:",
        "",
        f"{B}{S}",
        "if (address(refund).code.length == 0) { ",
        "    refund = refundEscrowFactory.newEscrow(poolId); ",
        "}",
        f"{B}",
        "",
        "The external factory contract's generation method (`newEscrow`) is protected by a strict authentication modifier (`auth`), meaning only pre-approved system addresses can trigger it. If the factory layer is deployed independently, the management contract will fail on its very first interaction cycle because it lacks explicit clearance within the factory's authorization database, resulting in a transaction rollback (`Auth: NotAuthorized()`).",
        "",
        "---",
        "",
        "## 2. Theoretical Exploit Scenario",
        "1. The protocol platform deploys both contract architectures onto the network.",
        "2. A user attempts to open a fresh pool configuration, triggering the contract's automated deployment loop.",
        "3. The contract attempts to request an escrow instance from the factory. The factory checks its access matrix, returns a `NotAuthorized` exception, and rolls back the user's transaction, preventing pool generation.",
        "",
        "---",
        "",
        "## 3. Remediation",
        "Ensure migration and deployment pipeline initialization scripts atomically link access permissions immediately following network instantiation loops:",
        "",
        f"{B}{S}",
        "// Deployment script sequencing implementation reference",
        "RefundEscrowFactory.rely(address(subsidyManager));",
        f"{B}"
    ],

    "UNCHECKED_ARITHMETIC_OVERFLOW.md": [
        "# Vulnerability Report: Unchecked Arithmetic Overflow in Staking Layout",
        "",
        "**Vulnerability Category:** Integer Overflow / State Manipulation",
        "**Severity:** High",
        "**Impact:** Staking Accounting Corruption / Theft of Contract Capital",
        "",
        "---",
        "",
        "## 1. Technical Analysis",
        "The legacy staking tracking ledger utilizes older compiler settings (`pragma solidity 0.4.11`) without embedding programmatic check-protection libraries like OpenZeppelin SafeMath. When adjustments run inside user deposit loops, properties are adjusted using raw arithmetic operators:",
        "",
        f"{B}{S}",
        "betterInfo[msg.sender].betAmount += msg.value;",
        "totalBetAmount += msg.value;",
        "totalAmountsBet[option] += msg.value;",
        f"{B}",
        "",
        "Because user-supplied values are added directly to state properties without overflow validation boundaries, an attacker can intentionally pass specific parameters to exceed maximum storage capacity bounds (`type(uint256).max`), forcing variables to wrap back around to zero.",
        "",
        "---",
        "",
        "## 2. Theoretical Exploit Scenario",
        "1. An attacker coordinates heavy capital deposits across explicit contract properties to force an overflow wrap-around inside total calculation values (`totalAmountsBet[winningOption]`).",
        "2. The tracking denominator wraps around to a nominal value close to zero.",
        "3. During automated redemption processing loops, the contract divides settlement pools by the corrupted tracking denominator, generating an inflated payout calculation that allows the attacker to drain the token pool:",
        "`payout = betAmount + (betAmount * losingChunk / totalAmountsBet[winningOption])`",
        "",
        "---",
        "",
        "## 3. Remediation",
        "Upgrade the system file pragma to standard modern defaults (`0.8.x`) to enforce native compiler-level overflow checks, or incorporate explicit utility validation libraries for legacy code bases:",
        "",
        f"{B}{S}",
        "import \"openzeppelin-solidity/contracts/math/SafeMath.sol\";",
        "",
        "contract Staking {",
        "    using SafeMath for uint256;",
        "    ",
        "    function bet(uint256 option) public payable {",
        "        betterInfo[msg.sender].betAmount = betterInfo[msg.sender].betAmount.add(msg.value);",
        "        totalBetAmount = totalBetAmount.add(msg.value);",
        "    }",
        "}",
        f"{B}"
    ],

    "REENTRANCY_STATE_VIOLATION.md": [
        "# Vulnerability Report: External Control-Flow Hijack via State-Check Delay",
        "",
        "**Vulnerability Category:** Reentrancy / CEI Pattern Non-Compliance",
        "**Severity:** High",
        "**Impact:** Asset Duplication / State Synchronization Bypass",
        "",
        "---",
        "",
        "## 1. Technical Analysis",
        "The registrar registration module transfers active domain resource identities to a secondary registry layer. During this processing step, the routine invokes an external call to pass records over to the new destination tracker:",
        "",
        f"{B}{S}",
        "// External invocation to an untrusted contract address",
        "Registrar(registrar).acceptRegistrarTransfer(_hash, h.deed, h.registrationDate);",
        "",
        "// State modification executed AFTER external transaction frame",
        "_entries[_hash].deed = Deed(0); ",
        f"{B}",
        "",
        "This sequence directly violates standard Check-Effects-Interactions protocol guidelines. The contract updates its local storage records to clear ownership registries *after* issuing the external transaction call frame, leaving an execution window wide open for a malicious recipient contract to re-enter the application loop.",
        "",
        "---",
        "",
        "## 2. Theoretical Exploit Scenario",
        "1. An attacker requests a asset registry transfer pointing to a malicious destination contract address.",
        "2. The registration hub processes the request and calls out to the target contract.",
        "3. The malicious recipient intercepts execution control flow and re-enters the registration hub's transfer function. Because the original storage record hasn't been set to zero yet, the secondary call block treats the attacker as the active owner, allowing them to duplicate registry records recursively.",
        "",
        "---",
        "",
        "## 3. Remediation",
        "Enforce strict Check-Effects-Interactions programming standards by completing all internal storage state adjustments before issuing external calls:",
        "",
        f"{B}{S}",
        "// Optimized Structural Sequence",
        "Deed deedToTransfer = _entries[_hash].deed;",
        "",
        "// Clear state records first",
        "_entries[_hash].deed = Deed(address(0)); ",
        "",
        "// Safely execute external transaction frame",
        "Registrar(registrar).acceptRegistrarTransfer(_hash, deedToTransfer, h.registrationDate);",
        f"{B}"
    ],

    "STORAGE_CONFIGURATION_FLAW.md": [
        "# Vulnerability Report: Inconsistent Balance Accounting via Storage Flag Misconfiguration",
        "",
        "**Vulnerability Category:** AMM Accounting Logic Flaw / State Desynchronization",
        "**Severity:** Medium",
        "**Impact:** Arbitrage Slippage Extraction / Liquidity Pool Draining",
        "",
        "---",
        "",
        "## 1. Technical Analysis",
        "A multi-asset stablecoin swap automated market maker (AMM) utilizes customized storage optimization patterns to track internal contract asset types. The configuration framework establishes an internal immutable flag during pool creation to indicate the presence of dynamic rebasing tokens (such as stETH):",
        "",
        f"{B}{V}",
        "self.pool_contains_rebasing_tokens = True  # Computed based on input array parameter indexes",
        f"{B}",
        "",
        "If a rebasing token asset type is introduced to the pool but its initialization parameters are misconfigured during initialization, the tracking flag remains `False`. The contract's main valuation calculation functions will skip live balance tracking lookups (`balanceOf(self)`), relying instead on the static cached internal balance registers:",
        "",
        f"{B}{V}",
        "# Vulnerable Balance Calculation Logic Flow",
        "if not self.pool_contains_rebasing_tokens:",
        "    return self.stored_balances[i]  # Returns stagnant cache values",
        f"{B}",
        "",
        "This breaks structural token pricing rules whenever automatic token rebasing events occur on-chain.",
        "",
        "---",
        "",
        "## 2. Theoretical Exploit Scenario",
        "1. A rebasing asset token is initialized into the stable swap liquidity pool with an incorrect asset type configuration index.",
        "2. An on-chain rebasing event triggers, causing the token's real contract balance to expand naturally.",
        "3. The liquidity pool ignores the real balance expansion because its state tracking relies on the static internal cache value.",
        "4. An arbitrageur notes the calculation mismatch, swaps against the pool using skewed asset pairs, and extracts the pricing delta at the expense of liquidity providers.",
        "",
        "---",
        "",
        "## 3. Remediation",
        "Dynamically track token balance differentials by comparing pre- and post-execution storage queries directly against the ERC20 token interface rather than relying on immutable configuration flags:",
        "",
        f"{B}{V}",
        "@internal",
        "def _transfer_out(_coin_idx: int128, _amount: uint256, receiver: address):",
        "    assert receiver != empty(address)",
        "",
        "    # Always cache balances pre and post to account for dynamic adjustments naturally",
        "    coin_balance_before: uint256 = ERC20(coins[_coin_idx]).balanceOf(self)",
        "    ",
        "    assert ERC20(coins[_coin_idx]).transfer(receiver, _amount, default_return_value=True)",
        "    ",
        "    # Update stored_balances based on actual change observed",
        "    self.stored_balances[_coin_idx] = coin_balance_before - ERC20(coins[_coin_idx]).balanceOf(self)",
        f"{B}"
    ]
}

print("📁 Generating anonymized security proof-of-concept files...")
for filename, lines in report_blueprints.items():
    filepath = os.path.join(REPORTS_DIR, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        # Dynamically write each clean line string down to disk natively
        f.write("\n".join(lines) + "\n")
    print(f"  ✅ Written: {filepath}")

print("\n🎯 Success! The parser completely bypassed layout collision boundaries.")
print("All 10 files are cleanly generated inside 'proof_of_concept_reports/'!")